name: E2E Test

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build e2e test image
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
        run: |
          docker build -t e2e -f Dockerfile.e2e . --build-arg ETH_RPC_URL=$ETH_RPC_URL

      - name: Run E2E Test
        run: docker run --rm e2e
