name: Release
# This workflow helps with creating releases.
# This job will only be triggered when a tag (vX.X.x) is pushed
on:
  pull_request:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write # for goreleaser/goreleaser-action to create a GitHub release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Create release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
